---
- name: playbook
  hosts: produccion
  remote_user: ubuntu
  become: true
  task:
    - name: git pull
      command: chdir=/home/ubuntu/practica4-sa git pull
    - name: stop container
      command: chdir=/home/ubuntu/practica4-sa sudo docker stop practica
    - name: remove container
      command: chdir=/home/ubuntu/practica4-sa sudo docker rm practica
    - name: remove image
      command: chdir=/home/ubuntu/practica4-sa sudo docker rmi imagen
    - name: build image
      command: chdir=/home/ubuntu/practica4-sa build -t imagen .
    - name: run
      command: chdir=/home/ubuntu/practica4-sa docker run --name practica -p 8081:4000 -d imagen