---
- name: playbook
  hosts: pruebas
  remote_user: pruebas
  become: true
  tasks:
    - name : git pull
      command: chdir=/home/ubuntu/practica4-sa git pull
    - name : stop container
      command: chdir=/home/ubuntu/practica4-sa docker stop practica
    - name : remove container
      command: chdir=/home/ubuntu/practica4-sa docker rm practica
    - name : remove image
      command: chdir=/home/ubuntu/practica4-sa docker rmi imagen
    - name : build image
      command: chdir=/home/ubuntu/practica4-sa docker build -t imagen .
    - name : run
      command: chdir=/home/ubuntu/practica4-sa docker run --name practica -p 8082:4000 -d imagen